# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'GearAnimation' do
  pod 'GearRefreshControl', path: '../'
end

target 'GearAnimationTests' do

end

use_frameworks!
